### ISSUE TITLE
mirrorMesh.py is broken with seissolxdmf v0.0.7

### ISSUE THREAD

**Issue by Radu-Raicea** [SeisSol/Meshing#15]
Since [these changes](https://github.com/SeisSol/Visualization/pull/3) were merged, running `mirrorMesh.py` with v0.0.7 of `seissolxdmf` fails because the reader was changed into a class.

**Comment by Radu-Raicea** [comment]
@Thomas-Ulrich @sebwolf-de

**Comment by Thomas-Ulrich** [comment]
Hi,
Yes I know, I will do that on Monday.
Thx,
Thomas.
