### ISSUE TITLE
place_receivers problem: Missing receivers

### ISSUE THREAD

**Issue by git-taufiq** [SeisSol/Meshing#7]
I got a problem while using the receivers' location generated by place_receivers. 
So, I run SeisSol using the new receiver location and it turned out not all receivers generated. I have 68 receiver points but only around 50 receivers generated. Some receivers are missing randomly. 
This is the parameter I used:
`place_receivers -d 0 -r receiver_noDepth.dat -m Model1 -o receiver_wDepth.dat`
Should I bury the receivers to a certain depth? ie. change -d from 0 m to -10 m?

**Comment by Thomas-Ulrich** [comment]
fixed by 482b4f9f6e86ab599c81d2b96216a25e8421f6ea
