### ISSUE TITLE
SimModeler download

### ISSUE THREAD

**Issue by brioglade** [SeisSol/Meshing#9]
Hi,
The link of SimModeler ( or modeling suite ) download link does't work.
How can I download it.I can not receive the download info although I have send a email to them twice.
Thank you very much for your help.

**Comment by Thomas-Ulrich** [comment]
Hi,
Here is your link
http://www.simmetrix.com/index.php/support/support-downloads

**Comment by brioglade** [comment]
Thanks a lot ! 😃

Thomas-Ulrich <notifications@github.com> 于2019年12月14日周六 下午12:58写道：
